import Head from "next/head";
import About from "../components/About";
import Landing from "../components/Landing";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>acosta codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Landing />
      <About />
      {/* education  */}
      {/* tech stack  */}
      {/* contact  */}
    </div>
  );
}
