import Head from "next/head";
import Main from "../components/Main";
import Navigation from "../components/Navigation";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>acosta codes blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navigation />
        {/* <Main /> */}
        {/* <div>" ↓ "</div> */}
      </main>
    </div>
  );
}
